version: '3'
services:
  ui:
    build:
      context: ./ui
    container_name: ui
    ports:
      - "3000:3000"
    networks:
      - internal_network

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "2137:2137"
    networks:
      - internal_network
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    networks:
      - internal_network
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=toor
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-logs:/opt/oracle/oraInventory

networks:
  internal_network:

volumes:
  oracle-data:
  oracle-logs: