version: '3'
services:
  ui:
    build:
      context: ./ui
    container_name: ui
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "2137:2137"
    depends_on:
      - oracle-db

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_SID=ORCLCDB1
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=toor
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=EE
      - ORACLE_VERSION=21.3.0
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-logs:/opt/oracle/oraInventory

volumes:
  oracle-data:
  oracle-logs: